import path from "node:path";
import { Command } from "commander";
import { chromium } from "playwright";
import {
  createLiveBridge,
  detectReader,
  preflightLiveMode,
} from "../live-bridge.js";

function readerOption(cmd) {
  return cmd
    .option(
      "--reader <name>",
      "Screen reader to use: voiceover or nvda (auto-detects OS by default)"
    )
    .option(
      "--start-timeout <ms>",
      "How long to wait for the screen reader to finish starting. Guidepup's " +
        "own default is 10s, which a cold VoiceOver start regularly exceeds.",
      "45000"
    );
}

// VoiceOver treats a web page as a sealed container. Stepping forward walks the
// browser's own chrome and then stops at the web-area boundary, where it
// announces "to enter the web area, press Control-Option-Shift-Down Arrow" —
// and says it literally, because forward movement alone will not descend. Every
// traversal therefore read Chrome's toolbar, stalled on that boundary, and the
// repeat-detector bailed once the same line came back three times. Zero page
// content, in both `read` and `test` (#11).
//
// `interact()` sends that command. NVDA has no equivalent boundary, so this is
// VoiceOver-only and a no-op elsewhere.
const WEB_AREA = /\bweb (?:content|area)\b|\bhtml content\b/i;

/**
 * Walk to the web-area boundary and step inside it.
 *
 * Returns { entered, skipped, boundary }. `skipped` holds whatever was
 * announced on the way — browser chrome, normally.
 *
 * On failure it hands those phrases back rather than swallowing them, because
 * the two failure modes are opposite: the boundary may be absent because
 * VoiceOver was *already* inside the page, in which case `skipped` is real page
 * content and discarding it would be the bug this function exists to fix.
 * The caller uses it as the start of the traversal instead.
 */
export async function enterWebArea(bridge, { maxProbe = 15 } = {}) {
  if (bridge.readerName !== "voiceover") {
    return { entered: false, skipped: [], reason: "not-voiceover" };
  }
  const skipped = [];
  for (let i = 0; i < maxProbe; i++) {
    const phrase = await bridge.next();
    if (!phrase) break;
    if (WEB_AREA.test(phrase)) {
      // interact() lands the cursor ON the first element inside the web area
      // and announces it. Calling next() from here would step PAST it, so the
      // page's first element — typically its h1 — would be missing from every
      // traversal. Capture what interact() announced and use it as entry one.
      const first = await bridge.interact();
      return { entered: true, skipped, boundary: phrase, firstPhrase: first };
    }
    skipped.push(phrase);
  }
  return { entered: false, skipped, reason: "boundary-not-found" };
}

/**
 * Walk backward through the page, logging what is announced.
 *
 * Exists because a whole class of defect is invisible going forward. A focus
 * guard that catches focus without direction awareness behaves perfectly in one
 * direction and misbehaves only in the other, so a forward-only tool reports a
 * clean pass on a page that is genuinely broken (#23).
 *
 * Three stop conditions, and the middle one is the finding:
 *
 * 1. Announcements run out — a normal, clean end.
 * 2. An element is announced twice — reverse navigation has wrapped instead of
 *    stopping at the boundary. This is the reported defect's actual signature,
 *    and it is structural, so it can be asserted rather than eyeballed.
 * 3. The walk steps back out of the web area into the browser's own chrome.
 *    Going backward past the top leaves the page, and those announcements are
 *    not the page, so they are dropped rather than logged as content.
 */
export async function walkBackward(bridge, { maxSteps = 100 } = {}) {
  const phrases = [];
  const seen = new Set();
  for (let i = 0; i < maxSteps; i++) {
    const phrase = await bridge.previous();
    if (!phrase) return { phrases, wrapped: false, reason: "end of page" };
    if (WEB_AREA.test(phrase)) {
      return { phrases, wrapped: false, reason: "stepped out of the web area" };
    }
    const key = normalisePhrase(phrase);
    if (seen.has(key)) {
      return {
        phrases,
        wrapped: true,
        reason: `repeat: reverse navigation returned to "${phrase.slice(0, 60)}" instead of stopping`,
      };
    }
    seen.add(key);
    phrases.push(phrase);
  }
  return { phrases, wrapped: false, reason: `step budget (${maxSteps}) reached` };
}

// VoiceOver adds coaching text of its own — "You are currently on…", "To move
// between items…", "To exit this web area…". It is generated by the reader, not
// the page, and it differs depending on which way you arrived at an element. So
// comparing raw phrases across directions reports a mismatch on every element
// and the comparison is useless. Strip it, and compare what the page said.
function normalisePhrase(phrase) {
  return (
    phrase
      .split(/\.\s*(?:You are currently on|To move between|To exit|To enter|To interact)/i)[0]
      // A container is announced on the way in and again on the way out — "list
      // 2 items" entering, "end of list" leaving — and which one you hear
      // depends on direction. They are one element, so collapse them, or every
      // list, dialog and table on the page reports as a one-sided difference
      // and buries the finding that matters.
      .replace(/^\s*end of\s+/i, "")
      // Positional chatter for the same reason: "1 of 2", "position 1",
      // "set size 2" describe where you are, not what the element is.
      .replace(/\b\d+ of \d+\b/gi, "")
      .replace(/\b(?:position|set size)\s+\d+\b/gi, "")
      .replace(/\b\d+ items?\b/gi, "")
      .replace(/[.,]/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .toLowerCase()
  );
}

/**
 * Compare the two logs and name what appears in only one of them.
 *
 * Deliberately not a verdict. Direction-specific phrasing is normal ("list 2
 * items" one way, "end of list" the other), so an exact mirror is the wrong
 * expectation and claiming to detect mis-ordering would produce noise a reader
 * learns to ignore. What is reportable is an element reached in one direction
 * and not the other — which is exactly the shape of the reported bug, where
 * swiping back out of a dialog reaches a menu item forward traversal never
 * visits. The two logs are printed in full so a human judges the rest.
 */
export function compareDirections(forward, backward) {
  const f = new Set(forward.map(normalisePhrase));
  const b = new Set(backward.map(normalisePhrase));
  const uniq = (list, other) => {
    const out = [];
    const added = new Set();
    for (const p of list) {
      const k = normalisePhrase(p);
      if (!other.has(k) && !added.has(k)) {
        added.add(k);
        out.push(p);
      }
    }
    return out;
  };
  return {
    forwardCount: forward.length,
    backwardCount: backward.length,
    onlyForward: uniq(forward, b),
    onlyBackward: uniq(backward, f),
  };
}

function reportEntry(entry, readerLabel) {
  if (entry.reason === "not-voiceover") return;
  if (entry.entered) {
    if (entry.skipped.length) {
      process.stderr.write(
        `(skipped ${entry.skipped.length} ${readerLabel} browser-UI item(s) before entering the page)\n`,
      );
    }
    return;
  }
  process.stderr.write(
    `\u26a0 Never reached the web-area boundary in ${entry.skipped.length} step(s). ` +
      `Reading from wherever the cursor started — output may include browser UI, ` +
      `or the page may already have been entered.\n`,
  );
}

export function liveCommand() {
  const live = new Command("live").description(
    "Drive a real screen reader (VoiceOver on Mac, NVDA on Windows)"
  );

  readerOption(
    live
      .command("open")
      .argument("<url>", "URL to open")
      .description("Open a URL and start the screen reader")
  ).action(async (url, opts) => {
    // Before a browser is launched or the screen reader is touched: if live
    // mode cannot work on this machine, say so now rather than after a timeout
    // with VoiceOver left half-started.
    const preflight = preflightLiveMode();
    if (!preflight.ok) {
      console.error(`\n${preflight.reason}\n`);
      process.exitCode = 1;
      return;
    }

    const bridge = await createLiveBridge(opts.reader);
    const browser = await chromium.launch({ headless: false });
    const page = await browser.newPage();

    const target =
      url.startsWith("http") || url.startsWith("file://")
        ? url
        : "file://" + path.resolve(url);

    await page.goto(target, { waitUntil: "domcontentloaded" });
    await bridge.start({ timeout: parseInt(opts.startTimeout, 10) });

    const readerLabel = bridge.readerName === "voiceover" ? "VoiceOver" : "NVDA";
    console.log(`${readerLabel} started on: ${target}`);
    console.log("Use the other live subcommands (next, previous, log) to navigate.");
    console.log("Press Ctrl+C to stop.\n");

    // Keep alive until user kills the process
    process.on("SIGINT", async () => {
      console.log("\nStopping screen reader...");
      await bridge.stop();
      await browser.close();
      process.exit(0);
    });

    // Block so the browser stays open
    await new Promise(() => {});
  });

  readerOption(
    live
      .command("read")
      .argument("<url>", "URL to read")
      .option("--steps <n>", "Max elements to traverse", "100")
      .option(
        "--direction <dir>",
        "forward (default), backward, or both. A focus guard that catches " +
          "focus without direction awareness looks perfect forward and " +
          "misbehaves only in reverse, so a forward-only read reports a clean " +
          "pass on a genuinely broken page. 'backward' walks to the end first, " +
          "then reverses; 'both' does each and reports what only one direction " +
          "reached.",
        "forward",
      )
      .option("--json", "Output as JSON")
      .description("Read the full page with a real screen reader and log what is announced")
  ).action(async (url, opts) => {
    // Before a browser is launched or the screen reader is touched: if live
    // mode cannot work on this machine, say so now rather than after a timeout
    // with VoiceOver left half-started.
    const preflight = preflightLiveMode();
    if (!preflight.ok) {
      console.error(`\n${preflight.reason}\n`);
      process.exitCode = 1;
      return;
    }

    const bridge = await createLiveBridge(opts.reader);
    const browser = await chromium.launch({ headless: false });
    const page = await browser.newPage();

    const target =
      url.startsWith("http") || url.startsWith("file://")
        ? url
        : "file://" + path.resolve(url);

    try {
      await page.goto(target, { waitUntil: "domcontentloaded" });
      await page.waitForTimeout(1000);
      await bridge.start({ timeout: parseInt(opts.startTimeout, 10) });

      const readerLabel0 =
        bridge.readerName === "voiceover" ? "VoiceOver" : "NVDA";
      const entry = await enterWebArea(bridge);
      reportEntry(entry, readerLabel0);

      const maxSteps = parseInt(opts.steps, 10);
      // On a failed entry the probe phrases are the start of the traversal, not
      // browser chrome to throw away — see enterWebArea. On a successful entry
      // the phrase interact() announced is the page's first element.
      const phrases = entry.entered
        ? entry.firstPhrase
          ? [entry.firstPhrase]
          : []
        : [...entry.skipped];

      const direction = opts.direction;
      if (!["forward", "backward", "both"].includes(direction)) {
        throw new Error(
          `--direction must be forward, backward or both (got "${direction}")`,
        );
      }

      for (let i = phrases.length; i < maxSteps; i++) {
        const phrase = await bridge.next();
        if (!phrase) break;
        phrases.push(phrase);

        // Some readers repeat when they hit the end
        if (phrases.length > 2) {
          const last3 = phrases.slice(-3);
          if (last3[0] === last3[1] && last3[1] === last3[2]) break;
        }
      }

      // Backward is always measured from the end, which is why the forward walk
      // above runs first even when only the reverse log is wanted: reversing
      // from the top of the page is a no-op, so "walk to the end, then back" is
      // the only reading that tests anything.
      let back = null;
      if (direction !== "forward") {
        back = await walkBackward(bridge, { maxSteps });
      }
      const comparison =
        direction === "both" ? compareDirections(phrases, back.phrases) : null;

      if (opts.json) {
        console.log(
          JSON.stringify(
            {
              url: target,
              direction,
              phrases,
              count: phrases.length,
              ...(back
                ? { backward: back.phrases, backwardStoppedBecause: back.reason, wrapped: back.wrapped }
                : {}),
              ...(comparison ? { comparison } : {}),
            },
            null,
            2,
          ),
        );
      } else {
        const readerLabel = bridge.readerName === "voiceover" ? "VoiceOver" : "NVDA";
        console.log(`\n${readerLabel} reading of: ${target}\n`);
        if (direction !== "backward") {
          console.log("  Forward:");
          phrases.forEach((p, i) => console.log(`   ${i + 1}. ${p}`));
        }
        if (back) {
          console.log(`\n  Backward (from the end):`);
          back.phrases.forEach((p, i) => console.log(`   ${i + 1}. ${p}`));
          console.log(`\n  Stopped: ${back.reason}`);
          if (back.wrapped) {
            console.log(
              `  ⚠ Reverse navigation WRAPPED instead of stopping at the boundary.`,
            );
          }
        }
        if (comparison) {
          console.log(`\n  --- Forward vs backward ---`);
          console.log(
            `  ${comparison.forwardCount} forward, ${comparison.backwardCount} backward`,
          );
          const list = (label, items) =>
            items.length
              ? console.log(`  ${label}:\n` + items.map((p) => `     ${p}`).join("\n"))
              : console.log(`  ${label}: none`);
          list("Reached only going forward", comparison.onlyForward);
          list("Reached only going backward", comparison.onlyBackward);
          console.log(
            `\n  Note: this names elements one direction reached and the other did not.\n` +
              `  It is not a verdict on ordering — a screen reader legitimately phrases\n` +
              `  the same element differently depending on which way you arrive at it.`,
          );
        }
        console.log(`\n(${phrases.length} announcements)`);
      }
    } finally {
      await bridge.stop();
      await browser.close();
    }
  });

  readerOption(
    live
      .command("test")
      .argument("<url>", "URL to test")
      .option("--json", "Output as JSON")
      .description("Run screen reader through the page and check for common issues")
  ).action(async (url, opts) => {
    // Before a browser is launched or the screen reader is touched: if live
    // mode cannot work on this machine, say so now rather than after a timeout
    // with VoiceOver left half-started.
    const preflight = preflightLiveMode();
    if (!preflight.ok) {
      console.error(`\n${preflight.reason}\n`);
      process.exitCode = 1;
      return;
    }

    const bridge = await createLiveBridge(opts.reader);
    const browser = await chromium.launch({ headless: false });
    const page = await browser.newPage();

    const target =
      url.startsWith("http") || url.startsWith("file://")
        ? url
        : "file://" + path.resolve(url);

    try {
      await page.goto(target, { waitUntil: "domcontentloaded" });
      await page.waitForTimeout(1000);
      await bridge.start({ timeout: parseInt(opts.startTimeout, 10) });

      const entry = await enterWebArea(bridge);
      reportEntry(
        entry,
        bridge.readerName === "voiceover" ? "VoiceOver" : "NVDA",
      );

      const phrases = entry.entered
        ? entry.firstPhrase
          ? [entry.firstPhrase]
          : []
        : [...entry.skipped];
      const issues = [];

      // Traverse the page
      for (let i = phrases.length; i < 200; i++) {
        const phrase = await bridge.next();
        if (!phrase) break;
        phrases.push(phrase);

        // Detect blank/empty announcements (unlabelled elements)
        if (phrase.trim() === "" || phrase.trim() === "blank") {
          issues.push({
            type: "empty-announcement",
            index: i + 1,
            message: "Screen reader announced blank/empty content — element may be missing an accessible name",
          });
        }

        // Detect repeated phrases that may indicate focus traps
        if (phrases.length > 2) {
          const last3 = phrases.slice(-3);
          if (last3[0] === last3[1] && last3[1] === last3[2]) {
            issues.push({
              type: "possible-loop",
              index: i + 1,
              phrase: phrase,
              message: `Screen reader appears stuck, repeating: "${phrase}"`,
            });
            break;
          }
        }
      }

      // Check heading navigation
      let headingPhrase;
      try {
        headingPhrase = await bridge.perform("moveToNextHeading");
      } catch {
        // Some readers don't support this command or no headings exist
      }

      if (opts.json) {
        console.log(
          JSON.stringify(
            {
              url: target,
              reader: bridge.readerName,
              totalAnnouncements: phrases.length,
              issues,
              phrases,
            },
            null,
            2
          )
        );
      } else {
        const readerLabel = bridge.readerName === "voiceover" ? "VoiceOver" : "NVDA";
        console.log(`\n${readerLabel} Test: ${target}`);
        console.log(`Announcements: ${phrases.length}`);

        if (issues.length === 0) {
          console.log("\nNo issues detected during screen reader traversal.");
        } else {
          console.log(`\nFound ${issues.length} potential issues:\n`);
          for (const issue of issues) {
            console.log(`  [${issue.type}] ${issue.message}`);
          }
        }

        console.log("\n--- Full Reading Log ---");
        phrases.forEach((p, i) => console.log(`  ${i + 1}. ${p}`));
      }
    } finally {
      await bridge.stop();
      await browser.close();
    }
  });

  return live;
}
